/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PillboxRouteImport } from './routes/pillbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermekProductIdRouteImport } from './routes/termek.$productId'
import { Route as GepMachineIdRouteImport } from './routes/gep.$machineId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PillboxRoute = PillboxRouteImport.update({
  id: '/pillbox',
  path: '/pillbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekProductIdRoute = TermekProductIdRouteImport.update({
  id: '/termek/$productId',
  path: '/termek/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const GepMachineIdRoute = GepMachineIdRouteImport.update({
  id: '/gep/$machineId',
  path: '/gep/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pillbox': typeof PillboxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gep/$machineId': typeof GepMachineIdRoute
  '/termek/$productId': typeof TermekProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pillbox': typeof PillboxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gep/$machineId': typeof GepMachineIdRoute
  '/termek/$productId': typeof TermekProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pillbox': typeof PillboxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gep/$machineId': typeof GepMachineIdRoute
  '/termek/$productId': typeof TermekProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pillbox'
    | '/sitemap.xml'
    | '/gep/$machineId'
    | '/termek/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pillbox'
    | '/sitemap.xml'
    | '/gep/$machineId'
    | '/termek/$productId'
  id:
    | '__root__'
    | '/'
    | '/pillbox'
    | '/sitemap.xml'
    | '/gep/$machineId'
    | '/termek/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PillboxRoute: typeof PillboxRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GepMachineIdRoute: typeof GepMachineIdRoute
  TermekProductIdRoute: typeof TermekProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillbox': {
      id: '/pillbox'
      path: '/pillbox'
      fullPath: '/pillbox'
      preLoaderRoute: typeof PillboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/$productId': {
      id: '/termek/$productId'
      path: '/termek/$productId'
      fullPath: '/termek/$productId'
      preLoaderRoute: typeof TermekProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gep/$machineId': {
      id: '/gep/$machineId'
      path: '/gep/$machineId'
      fullPath: '/gep/$machineId'
      preLoaderRoute: typeof GepMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PillboxRoute: PillboxRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GepMachineIdRoute: GepMachineIdRoute,
  TermekProductIdRoute: TermekProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
